[package]
authors = ["Kenichi Sato <ksato9700@gmail.com>"]
edition = "2018"
name = "bitcoind-zmq-watch"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.25"
zmq = "0.9"
